//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiFinda.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxi
    {
        public System.Guid id { get; set; }
        public string registration { get; set; }
        public string rank_name { get; set; }
        public string destination { get; set; }
        public decimal price { get; set; }
    }
}
