//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiFinda.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxiRank
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string area { get; set; }
        public string address { get; set; }
        public string taxis_available { get; set; }
    }
}
